packages:
  # all packages in subdirs of components/
  - 'tools/**'
  - 'frameworks/**'
  - 'node-basic/**'
  # exclude packages that are inside test directories
  # - '!**/test/**'
  # - '!entries/dist/**'
