packages:
  # all packages in subdirs of components/
  - 'vue/**'
  - 'react/**'
  - 'tools/**'
  - 'demos/**'
  # exclude packages that are inside test directories
  # - '!**/test/**'
  # - '!entries/dist/**'
