/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hashFile(filePath: string): string
export declare function plus100(input: number): number
export declare function fibonacci(input: number): number
