/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hashFile(filePathOrContent: string, isContent?: boolean | undefined | null): string
export declare function plus100(input: number): number
export declare function fibonacci(n: number): number
